### ISSUE TITLE
bug: Getting Client Registration Error

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/agama-openid#9]
On server: 

```
2024-02-28 22:37:13,672 INFO  [qtp1260134048-18] [server.register.ws.rs.action.RegisterCreateAction] (RegisterCreateAction.java:111) - Attempting to register client: applicationType = web, clientName = agama-openid-1709159833550, redirectUris = [https://caper.gluu.me/jans-auth/fl/callback], isSecure = true, sectorIdentifierUri = , defaultAcrValues = [], evidence =
2024-02-28 22:37:13,748 ERROR [qtp1260134048-18] [server.register.ws.rs.action.RegisterCreateAction] (RegisterCreateAction.java:191) - null
java.util.NoSuchElementException: null
        at java.util.ArrayList$Itr.next(ArrayList.java:970) ~[?:?]
        at io.jans.as.server.register.ws.rs.RegisterJsonService.getJSONObject(RegisterJsonService.java:157) ~[classes/:?]
        at io.jans.as.server.register.ws.rs.action.RegisterCreateAction.createClient(RegisterCreateAction.java:172) ~[classes/:?]
        at io.jans.as.server.register.ws.rs.RegisterRestWebServiceImpl.requestRegister(RegisterRestWebServiceImpl.java:52) ~[classes/:?]
        at io.jans.as.server.register.ws.rs.RegisterRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestRegister(Unknown Source) ~[classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

```

**Comment by nynymike** [comment]
Not sure if this is an error with the client, or if Auth Server should ignore the field if it's null (i.e. if it's not mandatory, it shouldn't throw an error).

**Comment by yuriyz** [comment]
It's bug on AS side which was fixed here: https://github.com/JanssenProject/jans/commit/761cc34af8b7a339d018d5770fc9c25c2a25ab5a

Latest war has it fixed: https://maven.jans.io/maven/io/jans/jans-auth-server/1.1.0-SNAPSHOT/jans-auth-server-1.1.0-SNAPSHOT.war
